### ISSUE TITLE
Was this change intended?

### ISSUE THREAD

**Issue by justinmcgrath** [biocro/biocro#112]
https://github.com/biocro/biocro/blob/31a414542d64513ba0c5425ee2b72fe651670fe5/src/module_library/c3photo.cpp#L175

Here GrossAssim is the same as Vc. However, it used to be An - Rd, in this version https://github.com/biocro/biocro/blame/98d70114460188e665dae052dcea1069b960bf2d/src/module_library/c3photo.cpp#L182.

I don't know that this is used anywhere and it's simply an informative variable, but I wanted to check that this was in fact intended.

**Comment by leavesandlemmas** [comment]
I came across `GrossAssim` while trying to compute the total assimilation rate  and the total respiration rate from BioCro. I am not entirely certain I understand the differences between `GrossAssim` and `canopy_assimilation_rate` and `net_assimilation_rate_*`. I am pretty certain that `canopy_assimilation = net_assimilation_rate_root + net_assimilation_rate_stem + ...` and `GrossAssim` appears to be the minimum of the rate of RuBP regeneration (limited by electron transport; `Vj`)  and the rate of carboxylation (`Vc`) but without any respiration subtracted. Can anyone confirm?

**Comment by eloch216** [comment]
> Here GrossAssim is the same as Vc. However, it used to be An - Rd

> I don't know that this is used anywhere and it's simply an informative variable, but I wanted to check that this was in fact intended.

This was an intentional change made by me. I think we had discussed it but maybe just in person. In the FvCB model, CO2 is captured via the CBB cycle and lost via photorespiration and mitochondrial respiration. We can see this in the equation for net assimilation: `An = (1 - GStar / C) * Vc - Rd = Vc - (GStar / C) * Vc - Rd`, where `(GStar / C) * Vc` is the rate of photorespiratory CO2 emission. Often in the literature, people use `An + Rd` as the gross assimilation rate. Yet, `An + Rd = (1 - Gstar / C) * Vc`, so it still includes photorespiratory losses and can in fact be negative (when `C < GStar`). This is not the usual sense of a "gross" rate. If we think of gross assimilation as the positive contribution to `An`, then it is identical to `Vc`. I realize this is a controversial point. If someone convinces me that `Ag = An + Rd` makes sense, I would be willing to change it.

You are correct that the gross rate is not used for any other calculations and is there just to be informative.

**Comment by eloch216** [comment]
> I am pretty certain that `canopy_assimilation = net_assimilation_rate_root + net_assimilation_rate_stem + ...`

This relationship is true, but that's not actually how these things are calculated. The canopy assimilation rate is calculated by one of the canopy assimilation modules (`c3_canopy`, `c4_canopy`, or `ten_layer_canopy_integrator`). Then this carbon is partitioned into the different tissue components by one of the partitioning calculators (`partitioning_growth_calculator`, `no_leaf_resp_partitioning_growth_calculator`, or `no_leaf_resp_neg_assim_partitioning_growth_calculator`). So, for example, `net_assimilation_rate_root` is the amount of assimilated carbon that is sent to the root for growth. It is probably a confusing name for this.

> `GrossAssim` appears to be the minimum of the rate of RuBP regeneration (limited by electron transport; `Vj`) and the rate of carboxylation (`Vc`) but without any respiration subtracted. Can anyone confirm?

Correct!

**Comment by leavesandlemmas** [comment]
> So, for example, `net_assimilation_rate_root` is the amount of assimilated carbon that is sent to the root for growth. It is probably a confusing name for this.

Maybe a better name would be something involving "allocation" like `carbon_allocation_rate_root` ?  That's what that quantity tends to be called.  For me, I just wanted to make sure I understood what the quantities are supposed to represent so I don't misinterpret them.

**Comment by leavesandlemmas** [comment]
>  If we think of gross assimilation as the positive contribution to `An`, then it is identical to `Vc`. I realize this is a controversial point. If someone convinces me that `Ag = An + Rd` makes sense, I would be willing to change it.

For me, gross assimilation just needs to be a strictly non-negative quantity. For instance, it should be zero in darkness. When modeling carbon allocation/NSC dynamics (and I suspect also nitrogen dynamics), the fact that net assimilation is not always positive creates problems. For NSCs, it basically means that net assimilation has to depend on their concentration. This is easy to achieve if gross assimilation is always non-negative and all respiration is what depends on NSCs.  I am not certain how photo-respiration factors in (haven't thought it enough). Photorespiration can still happen when atmo [CO2] is zero, so I guess that GrossAssim will make more sense as min(Vc, Vj).

**Comment by justinmcgrath** [comment]
I think that as far as terminology goes, this is a more sensible use of the the word "gross". I just couldn't remember a discussion about this. Maybe An - Rd is itself useful too, although offhand I can't think of a reason. Regardless, different name would make sense if someone was interested in it.
