### ISSUE TITLE
Update documentation workflow

### ISSUE THREAD

**Issue by gsrohde** [biocro/biocro#33]
Currently, this runs automatically mainly when a pull-request is made, and it only creates the documentation for download and won't publish it anywhere.  It _would_ attempt to publish if there were a push made to "master" (which doesn't exist) or if a version is tagged; or if the workflow were run manually with the "publish" option selected.  But it won't succeed because an SSH key granting the proper permissions has not been added to this repository, and if it did have those permissions, it would publish to the old `ebimodeling` location.

Should I add a new documentation location `biocro/biocro-documentation` inside this `biocro` organization?  Is there any reason to keep the `ebimodeling/biocro-documentation` repository?  This publishes to https://ebimodeling.github.io/biocro-documentation/.  Can we just have a single location for the documentation of the public version?  (That location will be https://biocro.github.io/biocro-documentation/ if we use `biocro/biocro-documentation` as the documentation repository unless we customize the URL to be something different.)

**Comment by eloch216** [comment]
My thoughts:

> Should I add a new documentation location `biocro/biocro-documentation` inside this `biocro` organization?

I vote yes. My intention is that any "official" BioCro information or sotware should all live in the `biocro` GitHub organization.

> Is there any reason to keep the `ebimodeling/biocro-documentation` repository? This publishes to https://ebimodeling.github.io/biocro-documentation/.

I vote no, based on the reasoning above. Could we move this repository to the `biocro` organization as we did with the main `biocro` repository? That way, anyone with old links to `ebimodeling/biocro-documentation` will get redirected to the new location.

> Can we just have a single location for the documentation of the public version? (That location will be https://biocro.github.io/biocro-documentation/ if we use `biocro/biocro-documentation` as the documentation repository unless we customize the URL to be something different.)

Yes, ideally there will be one single location for the BioCro documentation. That URL looks good to me.

**Comment by eloch216** [comment]
For long-term general organization, I want to suggest that besides the `main` branch, we also have an `unreleased` branch. The `unreleased` branch can be used for development, and changes can be collected there until we are ready to release a new version.

(In the long term, I want to remove the module library from `biocro/biocro`. When that's complete, it's unlikely that any development on `biocro/biocro` would need to be private, and can simply proceed on the `unreleased` branch.)

In that case, we might want to have documentation available for the `unreleased` branch, if only to help developers with making sure it looks correct. Public documentation for the `main` branch is a higher priority, though.

**Comment by gsrohde** [comment]
> For long-term general organization, I want to suggest that besides the `main` branch, we also have an `unreleased` branch. The `unreleased` branch can be used for development, and changes can be collected there until we are ready to release a new version. We could have branch protection rules to prevent any changes directly to `main`; instead, they should only occur via merging from `unreleased` to `main`.

I was just thinking about this yesterday.  I like the [git-flow](https://nvie.com/posts/a-successful-git-branching-model/) development model, which a colleague from NCSA put me onto 5 years ago when we were working on BETYdb together.  (He said they also used it for PEcAn and for other projects at NCSA.)

**Comment by justinmcgrath** [comment]
I agree with moving everything BioCro related to a single organization and not needed to keep anything in ebimodeling.

As far as moving vs recreating the documentation repository, I don't know the details of GitHub pages and don't plan to learn so I have no opinion about how it's done, but from the GitHub docs about transferring repositories, it doesn't seem like the GitHub pages will redirect.

"If the transferred repository contains a GitHub Pages site, then links to the Git repository on the Web and through Git activity are redirected. However, we don't redirect GitHub Pages associated with the repository." (https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository.)

I think that is a good workflow. In broad terms, that is what we have been doing with ebimodeling/biocro/main as the "main" branch and ebimodeling/biocro-dev/main as the "develop" branch, but with the large inconvenience of being in separate repositories, and then also a fair bit of chaos with multiple groups working on different "feature" branches that don't get merged regularly.

**Comment by eloch216** [comment]
> > Could we move this repository to the `biocro` organization as we did with the main `biocro` repository? That way, anyone with old links to `ebimodeling/biocro-documentation` will get redirected to the new location.
> 
> I would prefer to start fresh. This documentation is (mostly) automatically generated, and I don't see any compelling reason to keep its history. Is there a way to redirect without moving? If not, we could just put up a page at the old location that just has a link to the new one.

I can't seem to find anything obvious regarding redirecting a repository without moving it.

I would be concerned about out-dated and no-longer-managed documentation floating around in the internet. So, I would want to delete any old documentation from `ebimodeling/biocro-documentation`. In that case, any links that people might have saved would be dead, and a notice at `ebimodeling/biocro-documentation` wouldn't help with that situation. With this in mind, I think it might be better to simply delete that repository if we don't want to transfer it. (Does that make sense?)

**Comment by gsrohde** [comment]
> In that case, we might want to have documentation available for the `unreleased` branch, if only to help developers with making sure it looks correct. Public documentation for the `main` branch is a higher priority, though.

The way things work at `ebimodeling/biocro-dev` is that if documentation is published when working on a branch, the viewing location is

    https://ebimodeling.github.io/biocro-dev-documentation/<branch name>/pkgdown/index.html

But I suggest doing things slightly differently for biocro/biocro.

First, I'm not sure we need to publish documentation for unreleased code, though we could for convenience: the workflow by default makes a zip file containing all of the generated documentation.  For example, the documentation generated today is available at https://github.com/biocro/biocro/actions/runs/6709334277,
and you can download the [biocro-documentation](https://github.com/biocro/biocro/suites/17789895980/artifacts/1019588536) artifact, unzip it, and open the `biocro-docs-from-v3.0.0/pkgdown/index.html` file to see the main pkgdown page, which has links to all of the other documentation. (Side note: This build today was triggered by the addition of a tag, which by default is an action that causes the documentation to actually get published.  It's at https://ebimodeling.github.io/biocro-documentation/v3.0.0/pkgdown/index.html.  Apparently the SSH key got transferred along with the repository.)

Second, we do of course want to publish documentation for the latest release, and possibly for older releases as well.  I propose that the latest release documentation live at `https://biocro.github.io/biocro-documentation/index.html` if feasible, which would be the landing page for the pkgdown documentation, or possibly at `https://biocro.github.io/biocro-documentation/pkgdown/index.html`, `https://biocro.github.io/biocro-documentation/main/pkgdown/index.html`, or `https://biocro.github.io/biocro-documentation/latest/pkgdown/index.html` (or without the `pkgdown` component of the address, if feasible).  Older release documentation would be available at `https://biocro.github.io/biocro-documentation/<tag name>/pkgdown/index.html` (or just `https://biocro.github.io/biocro-documentation/<tag name>/index.html`, if feasible).

> I can't seem to find anything obvious regarding redirecting a repository without moving it.
>
> I would be concerned about out-dated and no-longer-managed documentation floating around in the internet. So, I would want to delete any old documentation from ebimodeling/biocro-documentation. In that case, any links that people might have saved would be dead, and a notice at ebimodeling/biocro-documentation wouldn't help with that situation. With this in mind, I think it might be better to simply delete that repository if we don't want to transfer it. (Does that make sense?)

No.  If the links are to the landing page at https://ebimodeling.github.io/biocro-documentation/, then there is no problem: that page can simply provide links to the new location.  But yes, there would be a problem if people have saved or published links to nested pages within the documentation.  So I suggest we keep the landing page (suitably revised), since that might at least help some people, and delete everything else.

**Comment by gsrohde** [comment]
> I propose that the latest release documentation live at `https://biocro.github.io/biocro-documentation/index.html` if feasible, which would be the landing page for the pkgdown documentation

Another possibility, one I think I may like better, is to have `https://biocro.github.io/biocro-documentation/index.html` be a link to a landing page containing links to the latest documentation and to the documentation of previous releases.

**Comment by justinmcgrath** [comment]
I'm not too concerned about the specific URL because I don't think anyone will notice, but https://biocro.github.io/biocro-documentation/index.html would be nice as the "home" URL since it's simplest.

If all of the docs pages can have a link to a page that itself has links to all of the versions, then I'd like the index to be for the latest version. From any version's home page, you could click "Other versions" or something like that to find the list of all versions.

**Comment by gsrohde** [comment]
> I'm not too concerned about the specific URL because I don't think anyone will notice, but https://biocro.github.io/biocro-documentation/index.html would be nice as the "home" URL since it's simplest.
> 
> If all of the docs pages can have a link to a page that itself has links to all of the versions, then I'd like the index to be for the latest version. From any version's home page, you could click "Other versions" or something like that to find the list of all versions.

For some perspective (or inspiration), it might be worth looking at PEcAn's public web page setup.

With GitHub Pages, you can publish a web site from any suitable GitHub repository.  But you can have, for each organization, one organization-wide site.  For PecanProject, this organization-wide site is published at https://pecanproject.github.io and corresponds to a repository named `PecanProject/pecanproject.github.io`.  (In general, an organization's Pages site will draw from a repository named `<organization>/<organization>.github.io` and publish to a URL called `https://<organization>.github.io`.)  This repository consists of manually-edited pages that don't change often.

But then there is the automatically-generated documentation.  The content for this is stored in the repository `PecanProject/pecan-documentation` and is published to subdirectories of https://pecanproject.github.io/pecan-documentation.  (In general, a Pages-enabled repository named `<organization>/<repository>` is published at `https://<organization>.gihub.io/<repository>`.  In this case, going to https://pecanproject.github.io/pecan-documentation itself will result in a "404 File not found" error since there is no top-level `index.html` file.)  The content of `PecanProject/pecan-documentation` is managed by a workflow in the repository `PecanProject/pecan`.

Although the content for the organization site, https://pecanproject.github.io, and the pecan-documentation site, https://pecanproject.github.io/pecan-documentation, are drawn from separate repositories, they are tied together by links from the organization site into the pecan-documentation site.  These links are on the page https://pecanproject.github.io/documentation.html, which you can get to via the Documentation menu item at the top of the home page of the organization site.

**Comment by eloch216** [comment]
> > I think it might be better to simply delete that repository if we don't want to transfer it. (Does that make sense?)
> 
> No. If the links are to the landing page at https://ebimodeling.github.io/biocro-documentation/, then there is no problem: that page can simply provide links to the new location. But yes, there would be a problem if people have saved or published links to nested pages within the documentation. So I suggest we keep the landing page (suitably revised), since that might at least help some people, and delete everything else.

Okay, let's leave it up and make sure it only contains a link to the new documentation site.

> > In that case, we might want to have documentation available for the `unreleased` branch, if only to help developers with making sure it looks correct. Public documentation for the `main` branch is a higher priority, though.
> 
> First, I'm not sure we need to publish documentation for unreleased code, though we could for convenience: the workflow by default makes a zip file containing all of the generated documentation. For example, the documentation generated today is available at https://github.com/biocro/biocro/actions/runs/6709334277, and you can download the [biocro-documentation](https://github.com/biocro/biocro/suites/17789895980/artifacts/1019588536) artifact, unzip it, and open the `biocro-docs-from-v3.0.0/pkgdown/index.html` file to see the main pkgdown page, which has links to all of the other documentation. 

I had forgotten that the documentation can be generated and downloaded using the workflow. In that case, I agree that we should only publish documentation for BioCro releases.

> Second, we do of course want to publish documentation for the latest release, and possibly for older releases as well. I propose that the latest release documentation live at `https://biocro.github.io/biocro-documentation/index.html` if feasible
> Older release documentation would be available at `https://biocro.github.io/biocro-documentation/<tag name>/pkgdown/index.html` (or just `https://biocro.github.io/biocro-documentation/<tag name>/index.html`, if feasible).
> 
> Another possibility, one I think I may like better, is to have `https://biocro.github.io/biocro-documentation/index.html` be a link to a landing page containing links to the latest documentation and to the documentation of previous releases.

> I'm not too concerned about the specific URL because I don't think anyone will notice, but https://biocro.github.io/biocro-documentation/index.html would be nice as the "home" URL since it's simplest.
> 
> If all of the docs pages can have a link to a page that itself has links to all of the versions, then I'd like the index to be for the latest version. From any version's home page, you could click "Other versions" or something like that to find the list of all versions.

I am not a huge fan of a landing page for the main documentation site (`https://biocro.github.io/biocro-documentation/index.html`). The landing page adds an extra layer of links that must be clicked through, but doesn't doesn't provide a benefit for most users -- I think that 99% of people visiting the site will be looking for documentation for the latest version. I like Justin's idea. Maybe there could be a page with links to all available versions at something like `https://biocro.github.io/biocro-documentation/version_index.html`. Then each `pkgdown` page could have a link to the version index.

**Comment by eloch216** [comment]
> For some perspective (or inspiration), it might be worth looking at PEcAn's public web page setup.

Thanks for sharing this.

I think we might want to make a BioCro organization page one day, as a way of providing a unifying description of all the separate repositories in the organization. I don't think we need to work on it right now because we have more pressing issues, but it's good to keep in mind.

For documentation, it sounds like we would mostly be following a similar scheme to PEcAn, except our equivalent to `https://pecanproject.github.io/documentation.html` will live in the documentation site rather than the organization site, and our equivalent to `https://pecanproject.github.io/pecan-documentation` will show the documentation for the latest version instead of an error message. I think this makes more sense for us, since it will allow us to get the documentation up and running without needing an organization site.

**Comment by gsrohde** [comment]
> I think we might want to make a BioCro organization page one day, as a way of providing a unifying description of all the separate repositories in the organization. I don't think we need to work on it right now because we have more pressing issues, but it's good to keep in mind.

I mainly wanted you all to be aware of what is possible.  I agree that we don't need to do this right now—it would involve a considerable amount of work.

**Comment by gsrohde** [comment]
> For documentation, it sounds like we would mostly be following a similar scheme to PEcAn, except our equivalent to `https://pecanproject.github.io/documentation.html` will live in the documentation site rather than the organization site, and our equivalent to `https://pecanproject.github.io/pecan-documentation` will show the documentation for the latest version instead of an error message. I think this makes more sense for us, since it will allow us to get the documentation up and running without needing an organization site.

I will start drafting changes to the documentation workflow and will set up the new documentation repository.

**Comment by gsrohde** [comment]
Completed by PR #36.
