### ISSUE TITLE
Can we delete the `soybean` branch?

### ISSUE THREAD

**Issue by eloch216** [biocro/biocro#35]
Link to branch in question: https://github.com/biocro/biocro/tree/soybean

I think this branch is a relic from the past when the `main` branch of this repository was the pre-module version of `BioCro`.

**Comment by justinmcgrath** [comment]
It looks like it has modules, so I'm not sure what this is. I think at one point I thought Soybean-BioCro was going in the same repository as everything and started moving things, before I knew it already had it's own place. Whatever it is, we don't need it.
