### ISSUE TITLE
Remove the "publish" option from manual dispatch of the documentation workflow?

### ISSUE THREAD

**Issue by gsrohde** [biocro/biocro#42]
From [this discussion in issue 33](https://github.com/biocro/biocro/issues/33#issuecomment-1789366158):

> > > In that case, we might want to have documentation available for the `unreleased` branch, if only to help developers with making sure it looks correct. Public documentation for the `main` branch is a higher priority, though.
> > 
> > 
> > First, I'm not sure we need to publish documentation for unreleased code, though we could for convenience: the workflow by default makes a zip file containing all of the generated documentation. For example, the documentation generated today is available at https://github.com/biocro/biocro/actions/runs/6709334277, and you can download the [biocro-documentation](https://github.com/biocro/biocro/suites/17789895980/artifacts/1019588536) artifact, unzip it, and open the `biocro-docs-from-v3.0.0/pkgdown/index.html` file to see the main pkgdown page, which has links to all of the other documentation.
> 
> I had forgotten that the documentation can be generated and downloaded using the workflow. In that case, I agree that we should only publish documentation for BioCro releases.

Although automatic publication of documentation now happens only when a new release is published, users still have the option to publish documentation when running the _Generate documentation_ workflow manually.  The documentation will appear at `https://biocro.github.io/BioCro-documentation/<branch name>/pkgdown/`, where `<branch name>` is the name of the branch on which the workflow is run, so this documentation won't clobber any documentation stemming from an official release.

Still, to avoid cluttering up the `biocro/BioCro-documentation` repository, I'm thinking maybe we should disable this behavior and not allow publication of documentation when a workflow is triggered manually.  The generated documentation is, after all, available as a download.  Alternatively, we could, for convenience, publish the generated documentation to an alternate location, `https://biocro.github.io/unreleased-documentation/<branch name>/pkgdown/` perhaps, with its own corresponding GitHub Pages site.

**Comment by eloch216** [comment]
> Still, to avoid cluttering up the `biocro/BioCro-documentation` repository, I'm thinking maybe we should disable this behavior and not allow publication of documentation when a workflow is triggered manually. The generated documentation is, after all, available as a download.

This sounds good to me.

> Alternatively, we could, for convenience, publish the generated documentation to an alternate location, `https://biocro.github.io/unreleased-documentation/<branch name>/pkgdown/` perhaps, with its own corresponding GitHub Pages site.

I think I'd rather not do this. Let's keep things simpler, and avoid having any possibly-incorrect documentation available on a documentation site.

**Comment by gsrohde** [comment]
> > Still, to avoid cluttering up the `biocro/BioCro-documentation` repository, I'm thinking maybe we should disable this behavior and not allow publication of documentation when a workflow is triggered manually. The generated documentation is, after all, available as a download.
> 
> This sounds good to me.
> 

OK, I'll work on this.

> > Alternatively, we could, for convenience, publish the generated documentation to an alternate location, `https://biocro.github.io/unreleased-documentation/<branch name>/pkgdown/` perhaps, with its own corresponding GitHub Pages site.
> 
> I think I'd rather not do this. Let's keep things simpler, and avoid having any possibly-incorrect documentation available on a documentation site.

We could call it something like "draft-BioCro-documentation" so it's clear.  But I'm fine with not doing this (less work for me).

**Comment by eloch216** [comment]
Do we need to keep this issue open?

**Comment by gsrohde** [comment]
I don't know what the policy should be.  I was going to leave it open with the "Fixed but not released" label until it actually _is_ released, but maybe it's enough that it has been merged into develop.

**Comment by justinmcgrath** [comment]
I could see a reason to have a "fixed but not released" label. Maybe someone has the latest release and see it fixed here, possibly being confused why they still see it. I tend to think that that will be rare, and anyone in that situation would sort it out themselves. Thus, keeping track of that label would be a maintenance task with little value.

Whether or not we use the label, it seems better to close the issue after it's merged with develop. It's nice to be able to assume that open issues are unfixed, without further subsetting them into open and fixed and open and unfixed.
